drbergman-lab/PhysiCellModelManager.jl

Project.toml
This pull request sets the compat entry for the `FFTW` package to `1`.
=> CompatHelper: add new compat entry for FFTW at version 1, (keep existing compat)

Project.toml
This pull request sets the compat entry for the `SQLite` package to `1`.
=> CompatHelper: add new compat entry for SQLite at version 1, (keep existing compat)

Project.toml
This pull request sets the compat entry for the `Statistics` package to `1`.
=> CompatHelper: add new compat entry for Statistics at version 1, (keep existing compat)

Project.toml
This pull request sets the compat entry for the `GlobalSensitivity` package to `2`.
=> CompatHelper: add new compat entry for GlobalSensitivity at version 2, (keep existing compat)

Project.toml
This pull request sets the compat entry for the `CSV` package to `0.10`.
=> CompatHelper: add new compat entry for CSV at version 0.10, (keep existing compat)

Project.toml
This pull request sets the compat entry for the `LazyGrids` package to `1`.
=> CompatHelper: add new compat entry for LazyGrids at version 1, (keep existing compat)

Project.toml
This pull request sets the compat entry for the `MAT` package to `0.10`.
=> CompatHelper: add new compat entry for MAT at version 0.10, (keep existing compat)

Project.toml
This pull request sets the compat entry for the `Distributions` package to `0.25`.
=> CompatHelper: add new compat entry for Distributions at version 0.25, (keep existing compat)

Project.toml
This pull request sets the compat entry for the `Sobol` package to `1`.
=> CompatHelper: add new compat entry for Sobol at version 1, (keep existing compat)

Project.toml
This pull request sets the compat entry for the `LightXML` package to `0.9`.
=> CompatHelper: add new compat entry for LightXML at version 0.9, (keep existing compat)

Project.toml
This pull request sets the compat entry for the `QuasiMonteCarlo` package to `0.3`.
=> CompatHelper: add new compat entry for QuasiMonteCarlo at version 0.3, (keep existing compat)

Project.toml
This pull request sets the compat entry for the `Tables` package to `1`.
=> CompatHelper: add new compat entry for Tables at version 1, (keep existing compat)

src/VCTVersion.jl
- was getting indices for milestones, not the version numbers
- switching to the config_variations tablename and its new index, didn't strip the " leading to error
=> fix milestones and up to 003

src/VCTClasses.jl, src/VCTDatabase.jl, src/VCTModule.jl, src/VCTPhysiCellVersion.jl, src/VCTRunner.jl, src/VCTUp.jl, src/VCTVersion.jl
- NULL in the index are no equal when compared. so instead fill out the commit hash with "$(commit_hash)-dirty"
- this will allow for unreproducible results, but gives the user the flexibility to work with a dirty repo
- it fixes the behavior where NULLs caused extra simulations and monads because they did not match
big bug fixes for physicell version
- monads and samplings, when selected, did not consider physicell version
- set global current_physicell_version_id inside createSchema so the db grabs the PhysiCell version on resetDatabase
- better warning message for dirty repos
- collectSimulationTasks(simulation::Simulation) only runs the sim if it is !isStarted (just like runMonad does)
- auto-upgrade to v0.0.11
=> if physicell repo dirty, add -dirty to hash

.github/workflows/CI.yml, docs/src/lib/VCTDatabase.md, docs/src/lib/VCTHPC.md, src/VCTAnalysis/population.jl, src/VCTAnalysis/substrate.jl, src/VCTClasses.jl, src/VCTCompilation.jl, src/VCTConfiguration.jl, src/VCTDatabase.jl, src/VCTDeletion.jl, src/VCTHPC.jl, src/VCTLoader.jl, src/VCTModule.jl, src/VCTMovie.jl, src/VCTPhysiCellStudio.jl, src/VCTPruner.jl, src/VCTRecorder.jl, src/VCTRunner.jl, src/VCTSensitivity.jl, src/VCTVariations.jl
- CI now uses env var PCVCT_NUM_PARALLEL_SIMS (instead of JULIA_NUM_THREADS) to control how many sims to run in parallel
- docs for VCTDatabase.jl and VCTHPC.jl
- use `outputFolder` to get path to `data/outputs/<types>/id
- allow for Trial to read in AbstractString for folders, not only String in some instances (point to update next)
- VCTCompilation.jl
- simplify documentation
- return bool indicating success of loadCustomCode
- compile in separate folder to make sure two processes do not interfere with compilation
- put the new PhysiCell in the AbstractSampling folder
- add a randomstring of 10 characters to the folder name
- delete the temp folder when finished compiling (after moving the executable to the inputs/custom_codes/folder folder)
- try-catch block for compilation errors so …
=> support sbatch on hpc

src/VCTClasses.jl, src/VCTCompilation.jl, src/VCTConfiguration.jl, src/VCTCreation.jl, src/VCTDatabase.jl, src/VCTRunner.jl, src/VCTSensitivity.jl, src/VCTVariations.jl, test/test-project/VCT/RunnerTests.jl, test/test-project/VCT/SensitivityTests.jl
- VariationIDs fields simplified (config_variation_id -> config, e.g.)
- ElementaryVariation now means a variation in a single parameter dimension
- ElementaryVariation as abstract type with DiscreteVariation and DistributedVariation as subclasses
- ElementaryVariations now store `location` \in `{:config, :rules, :ic_cell}` and `target` (in place of `xml_path`)
- set `location` in inner constructor
- length(dv::DiscreteVariation) -> length(dv.values)
- _runSensitivitySampling simpler
- sensitivitySampling replaced by just run
- refactor how ref var ids are read in during calls to addVariations
- simplify functions names prefixed with `get`
- doctest for DiscreteVariation
=> simplifying codebase

Project.toml, src/VCTClasses.jl, src/VCTConfiguration.jl, src/VCTCreation.jl, src/VCTDatabase.jl, src/VCTDeletion.jl, src/VCTExport.jl, src/VCTImport.jl, src/VCTModule.jl, src/VCTRunner.jl, src/VCTSensitivity.jl, src/VCTUp.jl, src/VCTUserAPI.jl, src/VCTVariations.jl, test/test-project/VCT/ClassesTests.jl, test/test-project/VCT/ConfigurationTests.jl, test/test-project/VCT/ICCellTests.jl, test/test-project/VCT/ImportTests.jl, test/test-project/VCT/PrunerTests.jl, test/test-project/VCT/RunnerTests.jl, test/test-project/VCT/SensitivityTests.jl, test/test-project/VCT/VariationsTests.jl
- standardizing rulesets_collection
- VariationIDs.rulesets_collection
- min_length->n_replicates
- createTrial
- also use_previous_simulations -> use_previous
- rulesets_variation_ids -> rulesets_collection_variation_ids
- `run` with same args as `createTrial`
- create `PCVCTOutput` to hold trial, n scheduled, and n success
- force_recompile set to false throughout
=> createTrial and run to simplify API

docs/make.jl, docs/src/man/covariations.md, docs/src/man/sensitivity_analysis.md, src/VCTConfiguration.jl, src/VCTCreation.jl, src/VCTICCell.jl, src/VCTModule.jl, src/VCTRunner.jl, src/VCTSensitivity.jl, src/VCTUserAPI.jl, src/VCTVariations.jl, test/runtests.jl, test/test-project/VCT/ConfigurationTests.jl, test/test-project/VCT/CreateProjectTests.jl, test/test-project/VCT/LoaderTests.jl, test/test-project/VCT/SensitivityTests.jl, test/test-project/VCT/UserAPITests.jl, test/test-project/VCT/VariationsTests.jl
- define CoVariation{T<:ElementaryVariation} <: AbstractVariation
- update createTrial and run calls to handle AbstractVariation (and thus the new CoVariation)
- createTrial can now take in a variation method as the first entry to run that kind of variation; without it, uses a GridVariation
- similarly, for run (see line up)
- new addVariations method for flexibility
- ParsedVariations now tracks `sz`, the size of each dimension of the variations fed into it
- ParsedVariations now also stores a copy of the variations fed into it
- simplify `addVariations(::GridVariation, ...)` to use new function `addLocationGridVariations`
- allow for CoVarariations when adding GridVariation
- getSimulationIDs on the `PCVCTOutput` object works
- UserAPI functions can now include an optional …
=> CoVariations

src/VCTVariations.jl, test/test-project/VCT/VariationsTests.jl
needs to accept vararg of `DiscreteVariation`s with possibly different datatypes (Int, Float64, etc)
=> fix CoVariation constructor

src/VCTDeletion.jl, src/VCTRunner.jl, test/test-project/VCT/HPCTests.jl, test/test-project/VCT/RunnerTests.jl
- referenced undefined vars causing hangups after erroring
- also created `SimulationProcess` struct to more elegantly handle pushing to `simulation_tasks` vector
- test sim with error
- test `SimulationProcess` as if running on HPC
- when running on hpc, rather than delete, move them to data_dir/.trash
- this avoids the issue of NFS not being able to delete files that are
open on another node, which could lead to hangups or errors
- within .trash, make directories day-specific, e.g. .trash/data-250208
- this makes them a bit easier to search through if the user wants to
- also add integer suffixes counting the duplicate file/folder names to avoid
overwriting files which again will cause NFS issues
=> fix error handling of sims; handle deletion on NFS

Project.toml, docs/src/misc/renaming.md, src/VCTClasses.jl, src/VCTDatabase.jl, src/VCTDeletion.jl, test/test-scripts/ClassesTests.jl, test/test-scripts/DatabaseTests.jl, test/test-scripts/RunnerTests.jl
- make sure monads record all simulations, even when using use_previous
- slightly improved api for creating monads
=> light fixes

README.md
Trying to add the PCVCT registry on a fresh Julia install without installing the general registry first gives a registry not-found error.
See here: https://forum.mimiframework.org/t/error-installing-mimi-under-v1-3-1/109/4
Error: (@v1.11) pkg> add pcvct
Updating registry at `~/.julia/registries/PCVCTRegistry`
Updating git-repo `https://github.com/drbergman/PCVCTRegistry`
Resolving package versions...
ERROR: cannot find name corresponding to UUID 995b91a9-d308-5afd-9ec6-746e21dbc043 in a registry
=> Update README.md with step to add general registry on fresh Julia install
